/*
 * This file is generated by jOOQ.
 */
package org.siu.rukawa.datasource.test.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -664578191;

    private Long    id;
    private String  name;
    private Integer age;
    private String  pass;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.pass = value.pass;
    }

    public Users(
        Long    id,
        String  name,
        Integer age,
        String  pass
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.pass = pass;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getPass() {
        return this.pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(pass);

        sb.append(")");
        return sb.toString();
    }
}
